Run patched CPython typing test suite

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,6 +6,7 @@ on:
   push:
     branches:
       - main
+      - run-patched-test_typing
   pull_request:
   workflow_dispatch:
 
@@ -101,6 +102,29 @@ jobs:
           directory: src
           fail_ci_if_error: true
           verbose: true
+
+      - name: Test CPython patched typing test suite
+        # Test suite fails on PyPy even without typing_extensions
+        if: ${{ !startsWith(matrix.python-version, 'pypy') }}
+        run: |
+          set -e
+          cd src
+          # Detect correct CPython branch
+          PY_VER="${{ matrix.python-version }}"
+          if [[ "$PY_VER" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            BRANCH="v$PY_VER" # use tag
+          else
+            BRANCH="$PY_VER" # use branch
+          fi
+          # Patch typing_extensions.py
+          cat <<'EOF' >> typing_extensions.py
+          TypedDict.__module__ = "typing"
+          def __getattr__(name):
+              return getattr(typing, name)
+          EOF
+          curl -fsSL "https://raw.githubusercontent.com/python/cpython/$BRANCH/Lib/test/test_typing.py" \
+          | sed 's/from typing /from typing_extensions /g; s/import typing/import typing_extensions as typing/g' \
+          | python -
 
   create-issue-on-failure:
     name: Create an issue if daily tests failed
